[project]
name = "ai-engineering-lab"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "ollama>=0.1.0",
    "langchain>=0.1.0",
    "langchain-community>=0.0.20",
    "openai>=1.12.0",
    "python-dotenv>=1.0.0",
    "httpx>=0.26.0",
    "pydantic>=2.5.0",
    "jupyter>=1.0.0",
    "ipykernel>=6.28.0",
    "llm",
    "llm-ollama",
    "llm-gpt4all",
    "instructor>=1.14.5",
    "langchain-ollama>=1.0.1",
    "langfuse>=3.14.5",
    "chromadb",
    "unstructured[md]>=0.21.5",
    "pypdf>=6.9.2",
    "langchain-chroma>=1.1.0",
]

[dependency-groups]
dev = [
    "pytest>=7.4.0",
    "ruff>=0.1.0",
]
